Document: net-snmp
Title: Debian net-snmp Manual
Author: <insert document author here>
Abstract: This manual describes what net-snmp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/net-snmp/net-snmp.sgml.gz

Format: postscript
Files: /usr/share/doc/net-snmp/net-snmp.ps.gz

Format: text
Files: /usr/share/doc/net-snmp/net-snmp.text.gz

Format: HTML
Index: /usr/share/doc/net-snmp/html/index.html
Files: /usr/share/doc/net-snmp/html/*.html
